<?php
namespace backend\filters;

use yii\base\ActionFilter;
use yii\web\ForbiddenHttpException;

class  RbacFilter extends ActionFilter{
    public function beforeAction($action)
    {
        //判断用户是否有权限进行操作,没有权限则抛出异常页面
        if(!\Yii::$app->user->can($action->uniqueId)){
            throw new ForbiddenHttpException('没有授权');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}